### PR TITLE
Base: TRIBAL

### PR DESCRIPTION
**Pull request by hiddentao**
Please review the following token assets:

## 📑 Description

Tribally is an entertainment platform where gamers compete and bet on each other. We provide games with groundbreaking social-fi protocols, making their games more fun and supercharging user growth.

- Token Name: `TRIBAL`
- Project Website: https://tribally.games
- Whitepaper: https://whitepaper.tribally.games/
- Explorer URI: https://basescan.org/address/0xe13e40e8fdb815fbc4a1e2133ab5588c33bac45d
- Coingecko: https://www.coingecko.com/en/coins/tribal-triballygames

---

## ✅ Checks

-   [x] I created a new folder with the token address (**all in lowercase** for EVM chains, **case sensitive** for Solana)
-   [x] I added the token's logo as a `32x32` PNG file, named `logo-32.png`
-   [x] I added the token's logo as a `128x128` PNG file, named `logo-128.png`
-   [x] I added the token's logo as a SVG file, named `logo.svg`
-   [x] My SVG logo is a proper SVG and does not contain base64 encoded elements
-   [x] My documentation/website clearly display the token address

### CODE REVIEW

**Comment by septio96** [comment]
good project

**Comment by tnkerer** [comment]
Bring me my $TRIBALs 

tenor

**Comment by abmisx0** [comment]
can you compress the SVG down a bit, the current size is a bit large. Here's a handy tool: https://jakearchibald.github.io/svgomg/

**Comment by hiddentao** [comment]
@abmisx0 We've already run it through that tool. The issue is the original logo was a PNG so we had to convert it to get an SVG.

**Review by abmisx0 — APPROVED** [review]

**Comment by hiddentao** [comment]
Thanks!

**Pull request merged**
