### PR TITLE
CTX token logo

### PR DESCRIPTION
**Pull request by voith**
Please review the following token assets:

## 📑 Description

-   Token Name: CTX
-   Project Website: https://cryptex.finance/
-   Explorer URI: https://basescan.org/address/0xBB22Ff867F8Ca3D5F2251B4084F6Ec86D4666E14

---

## ✅ Checks

-   [x] I created a new folder with the token address, **all in lowercase**
-   [x] I added the token's logo as a `32x32` PNG file, named `logo-32.png`
-   [x] I added the token's logo as a `128x128` PNG file, named `logo-128.png`
-   [x] I added the token's logo as a SVG file, named `logo.svg`
-   [x] My SVG logo is a proper SVG and not some base64 stuff
-   [x] My documentation/website clearly display the token address somewhere

### CODE REVIEW

**Comment by abmisx0** [comment]
can you upload a SVG smaller then `0.15MB` 
a logo redesign might be necessary but you can also compress the SVG using a tool like this: https://jakearchibald.github.io/svgomg/

**Comment by voith** [comment]
@abmisx0 I have pushed a new commit with a smaller svg. I managed to get it down to approximately 180 kb. Let me know if that works.

**Comment by abmisx0** [comment]
that's better but now the SVG logo has a base64 element. If you're converted from a PNG/JPG, please use this online tool as it converts without base64 elements: https://convertio.co/image-converter/

**Comment by voith** [comment]
@abmisx0 can you please take a look again?

**Review by abmisx0 — APPROVED** [review]

**Pull request merged**
